parameters:
#    challenge.example.class: TSP\ChallengeBundle\Example

services:
#    challenge.example:
#        class: %challenge.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
