challenge:
    resource: "@ChallengeBundle/Resources/config/routing.yml"
    prefix:   /

product_list:
    pattern: /productList
    defaults: { _controller: ChallengeBundle:ProductList:productList }
